name: Template
description: Preencher
title: " preencher "
body:
  - type: checkbox
    id: prioridade
    attributes:
      label: Selecione o nível de urgência dessa issue
      description:
       - label: Baixa
       - label: Média
       - label: Alta
       - label: Crítica
