name: "Nova tarefa"
description: "Template para criação de uma nova issue"
title: "[Tarefa] <inserir título aqui>"
labels: []
assignees: []

body:
  - type: input
    id: titulo
    attributes:
      label: "Título da tarefa"
      description: "Informe um título curto e objetivo"
      placeholder: "Ex: Implementar autenticação JWT"
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: "Descrição"
      description: "Explique o que precisa ser feito"
      placeholder: "Detalhes da tarefa..."
    validations:
      required: true

  - type: checkboxes
    id: prioridade
    attributes:
      label: "Prioridade"
      description: "Selecione o nível de prioridade"
      options:
        - label: "Crítica"
        - label: "Alta"
        - label: "Média"
        - label: "Baixa"
    validations:
      required: true

  - type: textarea
    id: comprovacao
    attributes:
      label: "Formas de comprovar a conclusão"
      description: "Liste como será possível verificar que a tarefa foi concluída"
      placeholder: "Ex: Prints de tela, testes passando, logs de execução..."
    validations:
      required: true
