name: Fechar Sprints Automáticas 

on:
  schedule:
    - cron: "0 3 * * *"  # Executa todo dia as zero hora do horario de Brasilia
  workflow_dispatch:

jobs:
  fechar-milestones: # Considere milestone como sprint e issues
    runs-on: ubuntu-latest

    steps:
      - name: Configurar GitHub CLI
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Debug milestones
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          gh api repos/$REPO/milestones --paginate | jq

      - name: Fechar issues e milestones que vencem hoje
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          # Ajusta a data atual para UTC-3 (Brasília)
          TODAY=$(date -u -d "-3 hours" +%Y-%m-%d)
          echo "Data atual (Brasília): $TODAY"

          # Lista milestones abertas e verifica se alguma vence hoje
          gh api repos/$REPO/milestones \
            --paginate \
            -q '.[] | select(.state=="open") | "\(.number) \(.title) \(.due_on)"' |
          while read NUMBER TITLE DUE_ON; do
            # Extrai data da due_on (ex: 2025-10-18T00:00:00Z → 2025-10-18)
            DUE_DATE=$(echo $DUE_ON | cut -d'T' -f1)

            if [ "$DUE_DATE" = "$TODAY" ]; then
              echo "Milestone \"$TITLE\" (#$NUMBER) vence hoje ($DUE_DATE). Fechando issues..."

              # Fecha issues abertas da milestone
              gh api repos/$REPO/issues \
                -f state=open \
                -f milestone=$NUMBER \
                --paginate \
                -q '.[] | .number' |
              while read ISSUE; do
                echo "Fechando issue #$ISSUE"
                gh api -X PATCH repos/$REPO/issues/$ISSUE -f state=closed
              done

              # Fecha a milestone
              echo "Fechando milestone \"$TITLE\""
              gh api -X PATCH repos/$REPO/milestones/$NUMBER -f state=closed
            fi
          done
