name: Fechar Milestones

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todo dia 00h Brasília (UTC+3)
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  fechar-milestones:
    runs-on: ubuntu-latest
    steps:
      - name: Ajusta a data atual para UTC-3 (Brasília)
        run: |
          TODAY=$(date -u -d "-3 hours" +%Y-%m-%d)
          echo "Data atual (Brasília): $TODAY"

          gh api repos/$REPO/milestones \
            --paginate \
            -q '.[] | select(.state=="open") | "\(.number) \(.title) \(.due_on)"' |
          while read NUMBER TITLE DUE_ON; do
            DUE_DATE=$(echo $DUE_ON | cut -d'T' -f1)
            if [ "$DUE_DATE" = "$TODAY" ]; then
              echo "Milestone \"$TITLE\" (#$NUMBER) vence hoje ($DUE_DATE). Fechando issues..."

              gh api repos/$REPO/issues \
                -f state=open \
                -f milestone=$NUMBER \
                --paginate \
                -q '.[] | .number' |
              while read ISSUE; do
                echo "Fechando issue #$ISSUE"
                gh api -X PATCH repos/$REPO/issues/$ISSUE -f state=closed
              done

              echo "Fechando milestone \"$TITLE\""
              gh api -X PATCH repos/$REPO/milestones/$NUMBER -f state=closed
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: Romm-0/testes
